### ISSUE TITLE
problem with solving CAPTCHAs

### ISSUE THREAD

**Issue by Ajoi1986** [akbaryahya/PokeBot#10]
If I let the bot doing its job, grinding up to 9000- 10000 XP within 30 minutes, the CAPTCHA will appear.
Even though I am able to solve it manually but somehow got problem in the next directed page i.e. The address wasn't understood. 
Therefore, I need to close the bot and open pokemon go app using my android smartphone to solve the CAPTCHA.

How to solve it? TQVM

![3](https://cloud.githubusercontent.com/assets/24926002/21918705/206870f6-d98f-11e6-8830-e426875c5c11.jpg)
![4](https://cloud.githubusercontent.com/assets/24926002/21918706/2068b444-d98f-11e6-92ed-68944f7c95df.jpg)

**Comment by akbaryahya** [comment]
You need to install
https://greasyfork.org/id/scripts/25036-captcha-pokemon-go
to get code response
