### ISSUE TITLE
0 Pokeballs it dosnt farm Pokestops after last Update :( !

### ISSUE THREAD

**Issue by Ozgudo** [akbaryahya/PokeBot#101]
![1](https://user-images.githubusercontent.com/32125318/30634197-94f379c4-9dee-11e7-9f07-643e808edc9c.PNG)
![2](https://user-images.githubusercontent.com/32125318/30634195-94035b6a-9dee-11e7-80ab-5c14a7a5f924.PNG)

**Comment by akbaryahya** [comment]
try new update

**Comment by Ozgudo** [comment]
I am using 2.0.4.3 is that not the newest one ?

**Comment by akbaryahya** [comment]
I really do not know your problem, but that seems like farm pokestops is running. if you are not sure check log (console)
