### ISSUE TITLE
Your domain down, cannot use bot.

### ISSUE THREAD

**Issue by rainfall77** [akbaryahya/PokeBot#106]
Error on the domain.  cannot use the bot now.

![image](https://user-images.githubusercontent.com/31579589/30770182-b6a84bb0-a05c-11e7-8366-eea4b2333171.png)

![image](https://user-images.githubusercontent.com/31579589/30770178-9fda566c-a05c-11e7-87b4-deb3816163fe.png)

**Comment by henryhenry1** [comment]
i agree , same is happening for me. :'( its double stardust today lol. i hope its back and running soon.

**Comment by akbaryahya** [comment]
go https://github.com/akbaryahya/PokeWP/issues/107
