### ISSUE TITLE
Why PokeWP down?

### ISSUE THREAD

**Issue by akbaryahya** [akbaryahya/PokeBot#107]
![azzzzjkjkj](https://user-images.githubusercontent.com/11765082/30770711-dcc65370-a069-11e7-834c-b1af686f06cf.jpg)
PokeWP/PokeMap/PokeWatch down because my vps get suspended (we also do not realize PokeWP users have so much, so the limit vps must be upgarded again).
if you want to help me send 20$ to https://www.paypal.me/siradiah/20 as a thank you, we will also give PokeWP Premium later.at this time i want to make it back again

**Comment by henryhenry1** [comment]
how fast would it be up ? when we transfer 20$?

**Comment by akbaryahya** [comment]
max one day,  there are some configs to be set up and the decision of vpsdime to unsuspend my vps

**Comment by henryhenry1** [comment]
ill send 20$ please let me know when up please ASAP plz , trying to take advantage of the double stardust .

**Comment by henryhenry1** [comment]
i sent funds :)

**Comment by henryhenry1** [comment]
my email is henrysanson@gmail.com

**Comment by akbaryahya** [comment]
I will try as soon make it back again ;)

**Comment by akbaryahya** [comment]
vps has been recovered, we will update the bot in 1 hour again, max 3 hours

**Comment by akbaryahya** [comment]
@henryhenry1 can you send key pokewp in akbaryahya_ym@yahoo.com I really thank you

**Comment by henryhenry1** [comment]
sent @akbaryahya to your email :)

**Comment by henryhenry1** [comment]
how can i get it to farm poke stops? cuz after it runs out of balls it just keeps walking only, and the pokestop farming is selected

**Comment by akbaryahya** [comment]
send last log in folder tmp

**Comment by henryhenry1** [comment]
Do you know what can be happening ? the bot program is working well and did before, but now it starts missing alot, i checked and i think it gets the account soft banned since the pokemon start becoming uncatchable even for me on phone?
