### ISSUE TITLE
Stuck at Starting login xxx

### ISSUE THREAD

**Issue by akbaryahya** [akbaryahya/PokeBot#11]
Problem at Reauthenticate
This problem only occurs if you do not have access token (new acc)
later fix

**Comment by Takumie** [comment]
im not using a new account but also facing token problem too. stuck at green sentence that says "try to connect with new token". It stuck there, and then a bulk of red error sentences come out. after that it tried to relogin but also stuck at green sentence "google login". ive waited for 20 mins still nothing so ive to restart the bot.

also this yellow message keep appearing
![token](https://cloud.githubusercontent.com/assets/13994233/22000991/eba71866-dc74-11e6-9f8f-be5ec1da3241.PNG)

**Comment by akbaryahya** [comment]
it just happens to google? btw can you upload full log? tmp/log.txt

**Comment by Takumie** [comment]
i dont know. but yes im using google account. i only have 1 account.
[log.txt](https://github.com/akbaryahya/PokeBot/files/710284/log.txt)
