### ISSUE TITLE
The pokemon go bot don't work any more

### ISSUE THREAD

**Issue by Felixitus** [akbaryahya/PokeBot#115]
Start login google stand there for 2 ours. Please fix it

**Comment by henryhenry1** [comment]
the niantic servers were down for while and now are up, it wasnt the bot

**Comment by coquidactylus** [comment]
Seems server are good now can we use bot safe again or we should wait for a new bot update?

**Comment by akbaryahya** [comment]
https://github.com/akbaryahya/PokeWP/issues/112#issuecomment-332298898

**Comment by henryhenry1** [comment]
what does this mean ?
![inkedscreenshot 71 _li upploaddd](https://user-images.githubusercontent.com/32214441/30892347-0319d382-a2ed-11e7-812c-3cd968e692e1.jpg)

**Comment by coquidactylus** [comment]
I wonder the same too! I been using the bot for few days now and wanned to buy hash and ask on how to buy premium key but that scares me what it means?

**Comment by JayGadhia** [comment]
Where do you guys bot? which city?

**Comment by akbaryahya** [comment]
just ignore message or buy a hash key so that the message does not appear always.
https://github.com/akbaryahya/PokeWP/wiki/Key-PokeHash&PokeWP
and POKEWP KEY AND HASH KEY have differences it's not the same

**Comment by Felixitus** [comment]
Vienna

Am 27.09.2017 06:57 schrieb "JayGadhia" <notifications@github.com>:
