### ISSUE TITLE
token expire

### ISSUE THREAD

**Issue by Ajoi1986** [akbaryahya/PokeBot#12]
just to inform
token expired and the bot stopped
happened twice

![token expired](https://cloud.githubusercontent.com/assets/24926002/22013763/a891837a-dcd5-11e6-89f5-4d27883d09d9.jpg)

**Comment by akbaryahya** [comment]
just stuck? and use google? btw try redownload 
https://github.com/akbaryahya/PokeBot/commit/34f36ffb59b443538476b481506a70ba8f04929e

**Comment by Titiocb13** [comment]
i use ptc account and i have the same issue 👍 
[11:40:31] Token Expire: 0 Days, 0 Hours, 0 Minutes, 0 sec
[11:40:31] If you frequently see this or time -1 please report to us
[11:40:31] Niantic: Token has expired, try to connect again with new token
[11:40:33] Error AggregateException: System.AggregateException: Une ou plusieurs erreurs se sont produites. ---> System.IO.IOException: Le processus ne peut pas accéder au fichier 'C:\Bot-Pokemon-GO\PokeBOTV1.0.5.2\tmp\titiocb13-ptc.json', car il est en cours d'utilisation par un autre processus.
   à System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   à System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   à System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   à System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   à System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   à System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   à PokemonGo.RocketAPI.Rpc.Login.SaveAccessToken(AccessToken accessToken) dans C:\Users\siakbary\Documents\Works\MyCode\PokemonGo.RocketAPI\Rpc\Login.cs:ligne 77
   à PokemonGo.RocketAPI.Helpers.RequestBuilder.<GetRequestEnvelope>d__30.MoveNext() dans C:\Users\siakbary\Documents\Works\MyCode\PokemonGo.RocketAPI\Helpers\RequestBuilder.cs:ligne 323
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PokemonGo.RocketAPI.Helpers.RequestBuilder.<GetRequestEnvelope>d__33.MoveNext() dans C:\Users\siakbary\Documents\Works\MyCode\PokemonGo.RocketAPI\Helpers\RequestBuilder.cs:ligne 367
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__3`2.MoveNext() dans C:\Users\siakbary\Documents\Works\MyCode\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:ligne 31
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PokemonGo.RocketAPI.Rpc.Inventory.<GetInventory>d__15.MoveNext() dans C:\Users\siakbary\Documents\Works\MyCode\PokemonGo.RocketAPI\Rpc\Inventory.cs:ligne 185
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PokemonGo.RocketAPI.Rpc.Inventory.<GetItems>d__12.MoveNext() dans C:\Users\siakbary\Documents\Works\MyCode\PokemonGo.RocketAPI\Rpc\Inventory.cs:ligne 156
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PokemonGo.RocketAPI.Rpc.Inventory.<GetItemAmountByType>d__38.MoveNext() dans C:\Users\siakbary\Documents\Works\MyCode\PokemonGo.RocketAPI\Rpc\Inventory.cs:ligne 415
   --- Fin de la trace de la pile d'exception interne ---
   à System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   à System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   à PokemonGo.RocketAPI.Logic.Logic.GetBestBerry(WildPokemon pokemon, IEnumerable`1 inventoryBerries)
   à PokemonGo.RocketAPI.Logic.Logic.catchPokemon(UInt64 encounter_id, String spawnpoint_id, PokemonId pokeid, Int64 cekjam)
   à PokemonGo.RocketAPI.Logic.Logic.ExecuteCatchAllNearbyPokemons()
   à PokemonGo.RocketAPI.Logic.Logic.HumanLikeWalking(GeoCoordinate targetLocation, Double walkingSpeedInKilometersPerHour, Boolean trackpoke, Boolean fromgoogle, Boolean stopat)
   à PokemonGo.RocketAPI.Logic.Logic.DoRouteWalking(Double latitude, Double longitude, Double walkspeed)
   à PokemonGo.RocketAPI.Logic.Logic.WalkPokestop()
   à PokemonGo.RocketAPI.Logic.Logic.ExecuteFarmingPokestopsAndPokemons(Boolean ulanglokasi, Boolean pokestop, Boolean pokemon, Boolean gysm, Double lat, Double lot, Boolean loadmap)
   à PokemonGo.RocketAPI.Logic.Logic.Execute()
---> (Exception interne #0) System.IO.IOException: Le processus ne peut pas accéder au fichier 'C:\Bot-Pokemon-GO\PokeBOTV1.0.5.2\tmp\titiocb13-ptc.json', car il est en cours d'utilisation par un autre processus.
   à System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   à System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   à System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   à System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   à System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   à System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   à PokemonGo.RocketAPI.Rpc.Login.SaveAccessToken(AccessToken accessToken) dans C:\Users\siakbary\Documents\Works\MyCode\PokemonGo.RocketAPI\Rpc\Login.cs:ligne 77
   à PokemonGo.RocketAPI.Helpers.RequestBuilder.<GetRequestEnvelope>d__30.MoveNext() dans C:\Users\siakbary\Documents\Works\MyCode\PokemonGo.RocketAPI\Helpers\RequestBuilder.cs:ligne 323
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PokemonGo.RocketAPI.Helpers.RequestBuilder.<GetRequestEnvelope>d__33.MoveNext() dans C:\Users\siakbary\Documents\Works\MyCode\PokemonGo.RocketAPI\Helpers\RequestBuilder.cs:ligne 367
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__3`2.MoveNext() dans C:\Users\siakbary\Documents\Works\MyCode\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:ligne 31
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PokemonGo.RocketAPI.Rpc.Inventory.<GetInventory>d__15.MoveNext() dans C:\Users\siakbary\Documents\Works\MyCode\PokemonGo.RocketAPI\Rpc\Inventory.cs:ligne 185
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PokemonGo.RocketAPI.Rpc.Inventory.<GetItems>d__12.MoveNext() dans C:\Users\siakbary\Documents\Works\MyCode\PokemonGo.RocketAPI\Rpc\Inventory.cs:ligne 156
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PokemonGo.RocketAPI.Rpc.Inventory.<GetItemAmountByType>d__38.MoveNext() dans C:\Users\siakbary\Documents\Works\MyCode\PokemonGo.RocketAPI\Rpc\Inventory.cs:ligne 415<---

[11:40:33] Error: System.IO.IOException: Le processus ne peut pas accéder au fichier 'C:\Bot-Pokemon-GO\PokeBOTV1.0.5.2\tmp\titiocb13-ptc.json', car il est en cours d'utilisation par un autre processus.
   à PokemonGo.RocketAPI.Logic.Logic.Execute()
   à PokeBOT.Program.<>c.<Main>b__11_0()
[11:40:33] Restarting in 20 Seconds. at program.cs
[11:40:53] Starting login: Ptc

**Comment by akbaryahya** [comment]
try redownload, I hope there is no problem anymore about token
https://github.com/akbaryahya/PokeBot/commit/4ddaa89f3a73eaf60263ba68ac1e8f917b53d46b

**Comment by Takumie** [comment]
nope. still stuck.
![stuck](https://cloud.githubusercontent.com/assets/13994233/22027576/e0a037c6-dd06-11e6-8c2f-ad515b1825ad.PNG)

**Comment by akbaryahya** [comment]
niantic message about token should be color yellow, please download patched version "4ddaa89", for now just stuck where get message niantic, if get "if you ...." it will not be stuck just waiting around minute

**Comment by Takumie** [comment]
ok its yellow, but ive waited for 10 minutes. still stuck. no bunch of error message like before thou. it just stuck there.

**Comment by Ajoi1986** [comment]
already updated patch version "4ddaa89"
still got niantic yellow colored message, twice so far.. one with "if you" and one without..


![token expire 2](https://cloud.githubusercontent.com/assets/24926002/22049622/717e10de-dd6f-11e6-85c1-57ea942328ff.jpg)
![token expire](https://cloud.githubusercontent.com/assets/24926002/22049621/717d8560-dd6f-11e6-9961-d7ed26412a1c.jpg)

**Comment by akbaryahya** [comment]
try download this https://github.com/akbaryahya/PokeBot/commit/defa7f9a4839a85bb2e074f1e4cab5edfc7fcae5 
I hope can be good news
