### ISSUE TITLE
What does this mean?

### ISSUE THREAD

**Issue by henryhenry1** [akbaryahya/PokeBot#121]
![screenshot 72](https://user-images.githubusercontent.com/32214441/31051485-785c91d2-a61e-11e7-8da8-bddaffb9f7f4.png)
servers are busy trying to connect 3secs

**Comment by henryhenry1** [comment]
<img width="1080" alt="2017-09-28" src="https://user-images.githubusercontent.com/32214441/31051592-00651822-a621-11e7-8aba-aa3b6db15a4a.png">
cant authenticate

**Comment by henryhenry1** [comment]
![screenshot 73](https://user-images.githubusercontent.com/32214441/31051599-3205241c-a621-11e7-991e-ff724827d3a2.png)
cant authenticate red letters

**Comment by akbaryahya** [comment]
server hash problem, not bot
