### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by LyrusZz** [akbaryahya/PokeBot#131]
Its maybe an issue but i dont know where i should ask.

- The bot uses the consumable incubators even when i click that it shouldnt use the 3 eggs or auto incubate
- It uses Pinapberrys on every pokemon. Is there an option that it just uses it on some pokemon?
- what does Battle GYM do? Does it just attack the gyms or does it just place an pokemon to the gyms and can he do the gymtutorial?
- lastly: can he do raids?

E: I looked a bit in the .json file and i could do it with the consumable incubators, but UsePinapBerry is on false and it's still using them.

**Comment by akbaryahya** [comment]
* I still do not understand
* Pinup Berry can now be set accordingly probability
* Battle Gym or raids only available for premium / private key users when available
