### ISSUE TITLE
Choosing pokemon for gym

### ISSUE THREAD

**Issue by Takumie** [akbaryahya/PokeBot#14]
bot always take random pokemon (mostly weak and low CP) for attacking even thou ive unchecked the randompokemon option. also when deploy i set it to MaxCP 1000 Max level 10 toppokemonexcluded 5, but got this error 

[00:01:20] Start Cek Gym Seed Form  Sculpture
[00:01:21] Members: 2. Level: 1
[00:01:21] Oh gym ghosts/team, let's put Pokemon in this gym
[00:01:23] Error: deployed.Count ~ 0/10

and end up puting my 44 CP magicarp to the gym.

i tried it again in the previous ver. 5.5, it choose correctly (Top CP pokemon for attacking) but got potion problem :/

**Comment by Titiocb13** [comment]
i have the same problem.
And in maxCP we can't put more than 2000

**Comment by akbaryahya** [comment]
hehe I know it should skip if total enemy team hp more, for now just not skip because reason debug

**Comment by Titiocb13** [comment]
I propose you can choose pokemons for attack and pokemons to put on a gym.

I have pokemon more than 3500 CP and bot put a 46 CP pokemon on a gym LOL

The bot choose Snorlax to attack, but i have dragonite / gyarados / Flareon and Vaporeon with best skills attack.

**Comment by akbaryahya** [comment]
is 46CP is lowest value of the list pokemon? I think there is a bug here
Pokemon can only be put if hp 100%

**Comment by Titiocb13** [comment]
Yes there is my lowest CP pokemon.

I test gym attack and after 15 fights, the bot choose always same pokemons to attack and never my best pokemons.

**Comment by akbaryahya** [comment]
I fixed put pokemon with high cp, about their attack based on the value in select high hp is not based on good skills, yes but I will try to make a choice
