### ISSUE TITLE
bot did not start

### ISSUE THREAD

**Issue by jensba23** [akbaryahya/PokeBot#141]
[28.10.2017 02:08:56] Error: Google.Protobuf.InvalidProtocolBufferException: SkipLastField called on an end-group tag, indicating that the corresponding start-group was missing
   bei Google.Protobuf.CodedInputStream.SkipLastField()
   bei POGOProtos.Networking.Envelopes.ResponseEnvelope.MergeFrom(CodedInputStream input)
   bei PokemonGo.RocketAPI.Extensions.HttpClientExtensions.PerformRemoteProcedureCall[TRequest](Client apiClient, RequestEnvelope requestEnvelope)
   bei PokemonGo.RocketAPI.Extensions.HttpClientExtensions.PerformThrottledRemoteProcedureCall[TRequest](Client apiClient, RequestEnvelope requestEnvelope)
   bei PokemonGo.RocketAPI.Extensions.HttpClientExtensions.PostProtoPayload[TRequest](Client apiClient, RequestEnvelope requestEnvelope, Type[] responseTypes)
   bei PokemonGo.RocketAPI.Rpc.BaseRpc.PostProtoPayload[TRequest](RequestEnvelope requestEnvelope, Type[] responseTypes)
   bei PokemonGo.RocketAPI.Rpc.BaseRpc.PostProtoPayload[TRequest,T1,T2](RequestEnvelope requestEnvelope)
   bei PokemonGo.RocketAPI.Rpc.Player.GetPlayer(Boolean addCommonRequests, Boolean addChallengeRequests)
   bei PokemonGo.RocketAPI.Client.DoLogin()
   bei PokeWP.Bot.StartBotx()

**Comment by henryhenry1** [comment]
how long have you been using the bot ?

**Comment by henryhenry1** [comment]
i got one of my accounts banned, I feel like its no longer safe

**Comment by umbreeon** [comment]
The bot is not safe anymore. I used the bot to Level my second Account (not my main) and the account got banned. I used it 2 times for 1-2 hours in my area with 1-9 km/h and the account still got banned. That happend one week ago. I never got any warning or anything.
