### ISSUE TITLE
Use Old version with pokehash

### ISSUE THREAD

**Issue by Titiocb13** [akbaryahya/PokeBot#15]
I launch the bot to day and, i see there is a new pogo api version

[19:40:20] ~ API BOT: 0.51.2 ~ API POGO: 0.53.1 -> Not safe, continued use you will force use old api

**Comment by akbaryahya** [comment]
the only warning you, for now app pogo still use 0.51.0, not force update
https://pgorelease.nianticlabs.com/plfe/version

**Comment by akbaryahya** [comment]
now force update, be safe

**Comment by Ajoi1986** [comment]
how to be safe?
less botting?

**Comment by Ajoi1986** [comment]
I was botting and probably the solve captcha came out but it not really came out and then the bot stopped
I opened PoGo using my smartphone and I got a freeze screen with nothing like this. Usually I will get 'you are robot' screen to solve. I tried uninstalling and reinstalling PoGo few times and the same freeze screen keep happening. Any idea?

![screenshot_20170120-130801](https://cloud.githubusercontent.com/assets/24926002/22136769/a58fdba2-df11-11e6-9af9-bba93d33933a.png)

**Comment by Ajoi1986** [comment]
![9](https://cloud.githubusercontent.com/assets/24926002/22139294/1d69eb82-df20-11e6-93d8-8c905fddd5f7.jpg)

the manual captcha window not appearing properly like before. It comes and goes unsolved just like than.

![10](https://cloud.githubusercontent.com/assets/24926002/22139298/23035dee-df20-11e6-993a-52894690e059.jpg)

**Comment by akbaryahya** [comment]
try download Google Chrome Dev
https://www.chromium.org/getting-involved/dev-channel

**Comment by Ajoi1986** [comment]
Problem solved.
I launched pokebot using personal laptop and it has no issue like that.
It seems that some desktops at my wokplace are outdated.
May be I should stop botting at workplace.
Thank you
