### ISSUE TITLE
Error pokeBot

### ISSUE THREAD

**Issue by Titiocb13** [akbaryahya/PokeBot#2]
Error: System.AggregateException: Une ou plusieurs erreurs se sont produites. ---> System.Exception: We received an unknown HttpStatusCode (ServiceUnavailable)..
   à PokemonGo.RocketAPI.Logic.Logic.<Execute>d__54.MoveNext()
   --- Fin de la trace de la pile d'exception interne ---
   à System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   à System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   à System.Threading.Tasks.Task.Wait()
   à PokeBOT.Program.<>c.<Main>b__11_1()
---> (Exception interne #0) System.Exception: We received an unknown HttpStatusCode (ServiceUnavailable)..
   à PokemonGo.RocketAPI.Logic.Logic.<Execute>d__54.MoveNext()<---

**Comment by Titiocb13** [comment]
it appears when I use pokehash key !
If a disable pokehash, i have no issue.

**Comment by akbaryahya** [comment]
Do you have key? if yes ,maybe because this issue
![thiswhy](https://cloud.githubusercontent.com/assets/11765082/21599910/eb3e44d8-d1ae-11e6-92eb-799a0c402627.jpg)

**Comment by Titiocb13** [comment]
Yes i have a key. I paid it this month and wait during developing VIP for donation.

Thank you.
