### ISSUE TITLE
Problem with pokehash key

### ISSUE THREAD

**Issue by Titiocb13** [akbaryahya/PokeBot#20]
![image](https://cloud.githubusercontent.com/assets/24854765/22344086/f4f8567c-e3fa-11e6-8676-cc23e9fa50d3.png)

My key is not expired

![image](https://cloud.githubusercontent.com/assets/24854765/22344131/321d242e-e3fb-11e6-933e-5d3615b3ec11.png)

**Comment by Titiocb13** [comment]
Not a pokehash issue, same problem without key.

There is a problem with your bot server

**Comment by akbaryahya** [comment]
this key pokebot not pokehash , I think check api down but now up do not worry
