### ISSUE TITLE
Bot stay in the same place with the new version

### ISSUE THREAD

**Issue by Titiocb13** [akbaryahya/PokeBot#22]
Hi,

before this version, tu bot catch lot of pokemons and farm lot of pokestops, after few hours :

![image](https://cloud.githubusercontent.com/assets/24854765/22388592/7f646fee-e4e1-11e6-86d5-9c07f323754a.png)

Now, after few hours, look the difference :

![image](https://cloud.githubusercontent.com/assets/24854765/22388625/a9266e86-e4e1-11e6-81f8-89eeddd88319.png)

Less pokemons and les pokestops, so less XP.

**Comment by akbaryahya** [comment]
the new feature logic walk to avoid got banned and merge all pokestop,gym,dbpoke,pokemon nearby to one walk, do not worry in next version will be better, like this :D
![unfdgdfgdfitled](https://cloud.githubusercontent.com/assets/11765082/22390237/d4b863c2-e524-11e6-8661-538029351fec.jpg)
