### ISSUE TITLE
Big problem happened, Restart in 8 seconds loop

### ISSUE THREAD

**Issue by ronie-san** [akbaryahya/PokeBot#25]
Hi .
I have the last version of the .exe but when it tries to login, the screen print this error, and keep printing it. I am not banned because I have tested my login in the phone.

**Comment by ronie-san** [comment]
[log.txt](https://github.com/akbaryahya/PokeBot/files/765115/log.txt)

**Comment by akbaryahya** [comment]
try download this https://github.com/akbaryahya/PokeBot/blob/master/addons/dll/dll_2342.zip
