### ISSUE TITLE
"Poke Watch" on website

### ISSUE THREAD

**Issue by oujinlong** [akbaryahya/PokeBot#32]
thanks for your web
we like it very much
but is there anything wrong with the "Poke watch" feature....
and is it can be normal like it before..?
thanks for all!

**Comment by akbaryahya** [comment]
about high IV? I had to fix it

**Comment by oujinlong** [comment]
No,the poke watch feature that can show the Pokémon I choose immediately before these days ,but it too slowly now and maybe won't show the Pokémon after waiting for a long time(the filter feature) 
Thanks for your web very much and sorry for my bad English

**Comment by akbaryahya** [comment]
is okay but I still do not understand, this about "Status: Server too busy 106.5%, Please try again later" or filter does not work or pokemon load very slowly?

**Comment by oujinlong** [comment]
filter does not work and pokemon load very slowly
it works quick before,and do not need to wait for a long time when i first time open it

**Comment by akbaryahya** [comment]
filter off from server (should already be on again) about slow it because it is doing scan pokemon (we add 25 feed location) or overload like "Server too busy 106.5%, Please try again later"

**Comment by oujinlong** [comment]
Yes,it work fine now
really thank you very much
hope you a nice day

**Comment by oujinlong** [comment]
what can i do that can hlep it
