### ISSUE TITLE
Issue after update.

### ISSUE THREAD

**Issue by AFluffyOrangutan** [akbaryahya/PokeBot#37]
So I stopped using this a while ago because I got board of Pokemon Go, and when I came back around I saw there was a new update so I downloaded it. And I then typed in my username and password and I started to get this error. Any help would be appreciated. 
[log.txt](https://github.com/akbaryahya/PokeBot/files/782396/log.txt)

**Comment by akbaryahya** [comment]
how about try new acc? is fine here ptc old&new

**Comment by AFluffyOrangutan** [comment]
Humm Ok I will make a new account and try that out and see if it works.
