### ISSUE TITLE
MAJ POGO 0.57 second generation

### ISSUE THREAD

**Issue by Titiocb13** [akbaryahya/PokeBot#38]
Since the new maj, there is new pokemons, but new items too.

Could you add the new items (NanabBerry / PinapBerry ...etc) on API ? Because we can't recycle or use them :)

**Comment by akbaryahya** [comment]
New api is ready, just need wait POGOProtos, btw you can recycle this item (by double-click, but auto yes not work xD)
![thispogo 2](https://cloud.githubusercontent.com/assets/11765082/23057385/eb24b71c-f52a-11e6-9399-548c6c343563.jpg)

**Comment by Takumie** [comment]
is old api work?

**Comment by akbaryahya** [comment]
yes but many captcha

**Comment by Titiocb13** [comment]
you can close this ticket, i opened a new suggestions ticket #43
