### ISSUE TITLE
Too Many Captcha 

### ISSUE THREAD

**Issue by jason86144** [akbaryahya/PokeBot#42]
I Am Getting Too Many Captcha In Five Minutes I Getted More than 20 Captchas @akbaryahya

**Comment by orignguyen** [comment]
Almost captchas were from spinning of pokestops.

**Comment by jason86144** [comment]
Can You Fix this Problem Or Not

**Comment by jason86144** [comment]
Please Fix this

**Comment by akbaryahya** [comment]
Do you use old api?

**Comment by jason86144** [comment]
No I'm Using 0.57.2

**Comment by jason86144** [comment]
I have to use this 0.45.0 I'm I right

**Comment by jason86144** [comment]
But where I write the API In Telegram Api key,Routing Google Api
key,2captcha Api key or Poke Hash Api key

Do you use old api?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/akbaryahya/PokeBot/issues/42#issuecomment-280923607>,
or mute the thread
