### ISSUE TITLE
Suggestions for future API BOT

### ISSUE THREAD

**Issue by Titiocb13** [akbaryahya/PokeBot#43]
Hi,

1) Add the check option on API (and live settings) to use NanabBerry and PinapBeery like RazzBerry

2) The value 51 is fixed on API (and live settings) to recycle NanabBerry and PinapBerry, so we can't put less or more

![image](https://cloud.githubusercontent.com/assets/24854765/23102034/d91dead4-f6a1-11e6-9351-0b213cc1de38.png)

3) Add possibility to use special objects (Sunstone, KingsRock ...) to evolve some pokemons (Porygon, Seadra, Slowpoke ...).
So the bot should check if pokemons are evolvable and if we have special objects before evolve them.
You can for example add a checkbox on API "Use special object to evolve"

4) Add enable/disable Gym attack on live settings

5) Reduce the timer between each pokemon's transferts when we want transfert some pokemons manually

**Comment by orignguyen** [comment]
I found gym attacking not as good as my expectation. Can you code to choose Pokemons with effective attack moves to gym defenders? For example, use Lapras with iced moves to attack Dragonize defenders, or pokemons with fighting moves to attack Snorlax. Anyway, it will be more convenience if you add enable/disable of gym attack on live setting. Thanks.
