### ISSUE TITLE
Where i can enter Api to use new Api Getting this error

### ISSUE THREAD

**Issue by jason86144** [akbaryahya/PokeBot#44]
![capture](https://cloud.githubusercontent.com/assets/25878356/23104476/65e382e0-f683-11e6-8d79-cea5a044c3ca.PNG)

**Comment by akbaryahya** [comment]
do you buy key pokehash? 
if yes contact https://github.com/akbaryahya/PokeBot/wiki/NEW-API#what-happens-if-force-updates-happen
if no or you use key pokebot? you must buy pokehash, because pokebot key NOT SUPPORT with pokehash key

**Comment by jason86144** [comment]
But How Can I use New Api

**Comment by akbaryahya** [comment]
please read again the above
