### ISSUE TITLE
Manual Evolve

### ISSUE THREAD

**Issue by Takumie** [akbaryahya/PokeBot#47]
Bot can't evolve pokemon with 2 possibilities for the non-item type if we don't have the evolution item even thou we have enough candy. for example, poliwhirl can't evolve to poliwrath because i don't have kingsrock, but poliwrath doesn't require kingsrock. only politoed does. also i notice for this kind of evolution the bot has identified both of the evolution are item-required type while only 1 in the game because its written N(100,1)|N(100,1)|C:101-0. shouldve Y(100)|N(100,1)|C:101-0.

how to fix: so when the candies are enough and we don't have the item-required the bot should be able to automatically evolve to the non-item type, but when we do have the evolution item, we should be able to choose which one we want to evolve into.

i found this not only for poliwhirl but also other pokemon with this kind of evolution like gloom. so im assuming it applies to every pokemon with this kind of evolution. i hope you get my point.

**Comment by akbaryahya** [comment]
so you want evolve without item if candies enough?

**Comment by Takumie** [comment]
if candy enough and i dont have the item, yes. only for evolution which have 2 different ways. like poliwhirl into poliwrath. but if i have the item to make poliwhirl into politoed, i wish somehow i still can choose whether i want to evolve it into poliwrath or politoed.

**Comment by Takumie** [comment]
so the logic is like this more or less.

check how many evolution possibilities
if possibilities>1 then
---check the item required
---if null then
------evolve to the one that doesnt require item (candy only)
---if yes then
------user choose whether evolve into the one that require item or the one that candy only.
