### ISSUE TITLE
error after somes snipes

### ISSUE THREAD

**Issue by Titiocb13** [akbaryahya/PokeBot#48]
![image](https://cloud.githubusercontent.com/assets/24854765/23204672/d2dfe4e0-f8e7-11e6-92b0-5380ce3c6f75.png)

**Comment by akbaryahya** [comment]
how many minutes stuck in there?

**Comment by Titiocb13** [comment]
just few seconds beetween 'Start Snipe' message and crash.

Another, but on the retour of snipe :

![image](https://cloud.githubusercontent.com/assets/24854765/23208104/09ba29ce-f8f4-11e6-96e3-7bc94dc16f1f.png)


So the is teleport that make this bug ?

**Comment by Titiocb13** [comment]
Can you add pokemon name on snipe tools ?
To snipe only the pokemon we want.

**Comment by akbaryahya** [comment]
This can happen: if GetMapObjet get null or internet slow or infinite loop,
why you need? add pokemon name, so you just want to focus snipe would you like to catch?

**Comment by Titiocb13** [comment]
yes just snipe the pokemon i would like to catch, not the others who are around.
