### ISSUE TITLE
Bug on level up

### ISSUE THREAD

**Issue by Titiocb13** [akbaryahya/PokeBot#51]
I juste level up from 38 to 39 :

![image](https://cloud.githubusercontent.com/assets/24854765/23457714/49ec7102-fe79-11e6-93d0-151f7d4e696c.png)

**Comment by Titiocb13** [comment]
same problem after restarting BOT

**Comment by akbaryahya** [comment]
wow level 39? I never thought there could be up to those levels, 3 million xp?

**Comment by Titiocb13** [comment]
there is same problem on 6.9 version.

Yes I'am lvl 39.
From 38 to 39 there were 3 million XP

So, I think to lvl up 40, it's 4 millions XP

**Comment by akbaryahya** [comment]
ok, can you testing this https://github.com/akbaryahya/PokeBot/commit/c725fca27de06d3af81cd53dd57b793b9dcfb777#diff-40cd5063c11b1d6f1dfd25da47e6060d ? I also changed some that may not work on gui

btw do you have problem Evolve Sunkern?

**Comment by Titiocb13** [comment]
The "starting" GUI is better and more beautiful than the last, but I have the same problem.

**Comment by akbaryahya** [comment]
same problem xp or evolve?

**Comment by Titiocb13** [comment]
Just XP.
I launch pogo on my phone, to lvl up from 39 to 40 there are 5 million xp.

**Comment by akbaryahya** [comment]
Now code use
https://gist.github.com/akbaryahya/518a1a7dc6a1b3938e414d638b990be1
is correct now?

**Comment by Titiocb13** [comment]
I answered on the post, it was not correct.

**Comment by Titiocb13** [comment]
to resume :

I am lvl 37, i have to win 2 500 000 xp to up lvl 38.
I am lvl 38, i have to win 3 000 000 xp to up lvl 39.
I am lvl 39, i have to win 5 000 000 xp to up 40.

**Comment by Titiocb13** [comment]
and there is no lvl more than 40 (for the moment, they said they'll creatin lvl 41 to 50 quickly, but i don't know how many xp to up on this lvl)

**Comment by akbaryahya** [comment]
https://github.com/akbaryahya/PokeBot/commit/f4eda2f319937a6727308f5b39d1d65dc6b4b1a6 
try again

**Comment by Titiocb13** [comment]
It's better ;)

![image](https://cloud.githubusercontent.com/assets/24854765/23524475/15077c08-ff8b-11e6-9fcd-ef2854460de4.png)
