### ISSUE TITLE
problem with farming pokestop V7.1

### ISSUE THREAD

**Issue by Titiocb13** [akbaryahya/PokeBot#53]
the bot try bot farm a pokestop, or i'am just under a GYM ...

![image](https://cloud.githubusercontent.com/assets/24854765/23571127/c6a1fd4e-0067-11e7-9b9b-423da832facc.png)

**Comment by Titiocb13** [comment]
same problem just near a pokestop

![image](https://cloud.githubusercontent.com/assets/24854765/23571210/3e1c6d64-0068-11e7-920c-c328becebd81.png)

**Comment by Titiocb13** [comment]
same problem with old version, so i think this is a problem on your server (or whith pogo upgrade ?), not in the bot (client).

**Comment by akbaryahya** [comment]
it could happen at any time, since UpdatePlayerLocate broken (Niantic kill her) we update the player using GetMapObject, so if you get "out of rage" that means GetMapObje not perform updates you current location or speed too fast

**Comment by Titiocb13** [comment]
I dont change anythink and it s work now.
