### ISSUE TITLE
Dont show the new pokemon

### ISSUE THREAD

**Issue by fronTAIR** [akbaryahya/PokeBot#59]
Hi!

Sorry my english!
The program does not show the new pokemons caught. This is my old acc. The bag was not empty.
![oldnewpokemon](https://cloud.githubusercontent.com/assets/26287090/23789014/58384586-0579-11e7-8f0b-2a4a574952df.jpg)

**Comment by fronTAIR** [comment]
The date format joke me. I use yyyy-mm-dd. The program use dd-mm-yyyy.

**Comment by akbaryahya** [comment]
you need reload it each catch, about date I will check it later

**Comment by fronTAIR** [comment]
Thank you very much for the update! Very good! Regards from Hungary!
