### ISSUE TITLE
UPDATE TOKEN?

### ISSUE THREAD

**Issue by Ajoi1986** [akbaryahya/PokeBot#6]
i tried using PokeBOTV1.0.5.5 but somehow this 'update token' thing keep on appearing in the black box.. and the speed catching pokemon also much slower than PokeBOTV1.0.5.4 in spite of similar pokemon catching setting

so i switched back using PokeBOTV1.0.5.4

**Comment by akbaryahya** [comment]
Can you provide screenshot problem? and upload tmp/log.txt
and what time zone used on your pc?

it seems I was wrong to set timezone token expired, here use GMT+8

**Comment by Ajoi1986** [comment]
(UTC+08:00) Kuala Lumpur, Singapore
![1](https://cloud.githubusercontent.com/assets/24926002/21880507/509f5c9a-d8da-11e6-9a91-502af01990b9.jpg)
![2](https://cloud.githubusercontent.com/assets/24926002/21880508/509f9692-d8da-11e6-9cbb-21d81e90080b.jpg)

**Comment by akbaryahya** [comment]
https://github.com/akbaryahya/PokeBot/blob/master/unpack/PokeBOT.exe
please download patch version, let us know if still problem

**Comment by Ajoi1986** [comment]
it becomes like this
Am I doing it wrong?

![5](https://cloud.githubusercontent.com/assets/24926002/21883250/2665ee1c-d8e9-11e6-9eb0-10ecd1c10b31.jpg)
![7](https://cloud.githubusercontent.com/assets/24926002/21883251/2669f4a8-d8e9-11e6-96be-11b371cac909.jpg)

**Comment by akbaryahya** [comment]
looks like you password gmail wrong or 2-step authentication, here is fine

**Comment by Ajoi1986** [comment]
problem fixed. thanks.

![8](https://cloud.githubusercontent.com/assets/24926002/21917028/a806b21c-d97f-11e6-8636-a5bb1976342b.jpg)

**Comment by akbaryahya** [comment]
I'm glad it worked ^_^
