### ISSUE TITLE
The program stops at the lure

### ISSUE THREAD

**Issue by fronTAIR** [akbaryahya/PokeBot#60]
always find a lure
![kep](https://cloud.githubusercontent.com/assets/26287090/23815048/6858be9c-05e6-11e7-92e3-95c000f4d95a.png)

**Comment by akbaryahya** [comment]
do you disable catch lure pokemon? and can you send tmp/log.txt

**Comment by fronTAIR** [comment]
![kep](https://cloud.githubusercontent.com/assets/26287090/23821029/84effaca-0627-11e7-8010-8ba997f4a50b.png)

[log.txt](https://github.com/akbaryahya/PokeBot/files/835547/log.txt)

**Comment by akbaryahya** [comment]
can you update with this https://github.com/akbaryahya/PokeBot/commit/f7ec5ff56a06b7391154e02a2493b3f8c06ee38a and test it and let me know that I was working or not

**Comment by fronTAIR** [comment]
Good! Thanks!

![screenshot 2017-03-11 13 50 05](https://cloud.githubusercontent.com/assets/26287090/23823407/078e7a9e-0662-11e7-9bdf-b0216715c2bc.png)
