### ISSUE TITLE
How to fix :- Your ip has been banned for 5 minutes

### ISSUE THREAD

**Issue by jason86144** [akbaryahya/PokeBot#61]
When i open pokebot and i use trail Api After the pokebot started Catching Pokemon After sometime pokebot Says Ip has  Been Banned For 5 Minutes And Again And again And If i wanted to use old api Pokebot Says 
![capture1](https://cloud.githubusercontent.com/assets/25878356/23830849/4824d1f6-06d1-11e7-81c4-ba9a86d510e7.PNG) How to fix

**Comment by akbaryahya** [comment]
api old is die if you use it you got auto ban, about "Ip has Been Banned For 5 Minutes" it was only banned from my server bacuase key free overload

**Comment by jason86144** [comment]
So how can I fix it

**Comment by akbaryahya** [comment]
just update it

**Comment by jason86144** [comment]
But how can I use new api

**Comment by akbaryahya** [comment]
https://github.com/akbaryahya/PokeBot/wiki/NEW-API
