### ISSUE TITLE
No farm pokestop, why?

### ISSUE THREAD

**Issue by fronTAIR** [akbaryahya/PokeBot#62]
[10:28:06] Stats: resetcoutxp: 18 ~ resetcout: 2 ~ usepokerare: 18

?????

[log.txt](https://github.com/akbaryahya/PokeBot/files/850143/log.txt)

**Comment by akbaryahya** [comment]
I think it works, about "Stats: resetcoutxp: 18 ~ resetcout: 2 ~ usepokerare: 18" is just stats just ignore it

**Comment by fronTAIR** [comment]
No farming..... All ball zero.... No spin pokestop..... The account is not softbanned.
![screenshot 2017-03-17 18 54 34](https://cloud.githubusercontent.com/assets/26287090/24056256/455236a0-0b43-11e7-8291-1329332b6080.png)
![screenshot 2017-03-17 18 54 45](https://cloud.githubusercontent.com/assets/26287090/24056268/54779c92-0b43-11e7-9be4-7858bbaa7389.png)

Look, the pokestop to stay blue!

[log.txt](https://github.com/akbaryahya/PokeBot/files/851380/log.txt)

**Comment by akbaryahya** [comment]
try this https://github.com/akbaryahya/PokeBot/commit/d85adf8db88d98b41ddcfab310ea8bea017a77bb and can you provide snapshot in start->settings->walk?

**Comment by fronTAIR** [comment]
![kep](https://cloud.githubusercontent.com/assets/26287090/24061386/8b015bf4-0b57-11e7-9916-b9fcba8aab04.png)
I look at that now to farm pokestop?
![kep](https://cloud.githubusercontent.com/assets/26287090/24061489/e905b68c-0b57-11e7-8cb2-26da8650fdd5.png)
Looks good!

**Comment by fronTAIR** [comment]
Hey he did not come back from the snipe! :((
[log.txt](https://github.com/akbaryahya/PokeBot/files/851718/log.txt)
Now is ok! I was a little scared.

**Comment by akbaryahya** [comment]
Well I hope this fix it ;) , If is still problem please comment again
