### ISSUE TITLE
why not fight?

### ISSUE THREAD

**Issue by fronTAIR** [akbaryahya/PokeBot#63]
Hello! I again....

![kep](https://cloud.githubusercontent.com/assets/26287090/24071454/5ba01848-0bd2-11e7-8110-46b5280e9134.png)

**Comment by akbaryahya** [comment]
total hp greater than your team

**Comment by fronTAIR** [comment]
no problem.... more circle...

**Comment by akbaryahya** [comment]
please try latest version
