### ISSUE TITLE
BOT don't collect coins

### ISSUE THREAD

**Issue by Titiocb13** [akbaryahya/PokeBot#64]
![image](https://cloud.githubusercontent.com/assets/24854765/24320586/99300a4a-1138-11e7-89dd-74681a0cc34c.png)

before with old versions the bot collect coin if one pokemon is on a gym.
Now it'seems only collect coin if you have 9 pokemons on gyms

**Comment by akbaryahya** [comment]
yes for temporarily you must have 9 pokemon in gym, if you have one and then pick it up it will make error Session Invalidate
