### ISSUE TITLE
It's not coming back after a teleport.

### ISSUE THREAD

**Issue by fronTAIR** [akbaryahya/PokeBot#65]
Many times it happened.

![kep](https://cloud.githubusercontent.com/assets/26287090/24321235/ac9490d8-1147-11e7-861e-fac1bb7455ca.png)
[log-20170325.txt](https://github.com/akbaryahya/PokeBot/files/869903/log-20170325.txt)

**Comment by akbaryahya** [comment]
can you try this, with this will make it clear about what error https://github.com/akbaryahya/PokeBot/commit/e1ebefb8eba14f6f58569f12fbe1d8833606ef39 ?
I still do not understand an error message "Error: A szál megszakadt."

**Comment by fronTAIR** [comment]
Looks good! I found ok! THX!
But no evolves and does not transfer. Only 1-2 Pokémon Transfer, nothing evolve. Previous versions did not.

**Comment by akbaryahya** [comment]
can you send log?
