### ISSUE TITLE
When I upgrade, download the old version!

### ISSUE THREAD

**Issue by fronTAIR** [akbaryahya/PokeBot#68]
When I upgrade, download the old version! I tried to download it from the GitHub, there is also the old zip file ...

![kep](https://cloud.githubusercontent.com/assets/26287090/24585334/0d4396d6-1788-11e7-9b63-5300973264c5.png)

**Comment by akbaryahya** [comment]
Thank you tell me, I'll update later file

**Comment by akbaryahya** [comment]
try https://github.com/akbaryahya/PokeBot/releases/download/1.0.8.2/PokeBOTV1.0.8.2-b.exe

**Comment by fronTAIR** [comment]
THX!

![kep](https://cloud.githubusercontent.com/assets/26287090/24585591/3332719e-178f-11e7-894b-39e255b0a442.png)

**Comment by fronTAIR** [comment]
![kep](https://cloud.githubusercontent.com/assets/26287090/24585656/217380fa-1790-11e7-95b8-feeb31e63c47.png)
[log-20170402.txt](https://github.com/akbaryahya/PokeBot/files/888261/log-20170402.txt)

**Comment by akbaryahya** [comment]
This is still experimental, maybe you will see many error code SessionInvalidated
