### ISSUE TITLE
Pb with Gym when pokemon die and have no revive

### ISSUE THREAD

**Issue by Titiocb13** [akbaryahya/PokeBot#7]
[18:23:18] We were victorious!: 
[18:23:24] Pokemon: Dragonite | ST:0/149
[18:23:24] You pokemon die, try use item revive
[18:23:28] BAD
[18:23:28] Pokemon: Snorlax | ST:0/254
[18:23:28] You pokemon die, try use item revive
[18:23:34] BAD
[18:23:34] Pokemon: Gyarados | ST:145/155
[18:23:34] You pokemon fine but critical, try use item potion
[18:23:34] Pokemon: Gyarados | ST:151/151
[18:23:34] You pokemon fine
[18:23:34] Pokemon: Snorlax | ST:246/246
[18:23:34] You pokemon fine
[18:23:34] Pokemon: Vaporeon | ST:203/203
[18:23:34] You pokemon fine
[18:23:37] Attacking Gym: La Grande Roue, DefendingPokemons:
Exeggutor
Rhydon
Exeggutor, 
Attacking: Exeggutor
[18:23:38] Start battle failed...., Error: PokemonGo.RocketAPI.Exceptions.InvalidResponseException: BAD REQUEST 
{"StatusCode":2,"RequestId":1224334123405937087,"Requests":[{"RequestType":135,"RequestMessage":[10,35,56,56,55,49,50,55,53,48,51,101,56,57,52,56,48,99,57,55,102,57,97,98,51,101,57,99,49,55,99,50,56,98,46,49,54,18,48,146,46,12,37,41,37,128,204,218,217,221,23,174,226,152,44,211,17,196,31,103,93,136,109,151,187,188,152,178,17,124,214,60,69,72,216,247,12,138,172,29,85,59,83,110,154,170,227,25,84,157,172,148,163,184,140,163,33,136,239,218,27,124,249,69,64,41,81,83,217,104,228,51,19,64]}],"PlatformRequests":[{"Type":6,"RequestMessage":[10,133,4,147,169,57,2,212,130,28,165,130,206,20,111,172,121,92,150,163,199,157,74,30,140,89,245,85,197,6,254,23,244,109,129,227,242,156,192,179,81,173,194,166,168,195,15,175,108,138,26,88,7,47,195,186,236,224,102,132,133,184,121,232,70,77,115,54,255,80,201,145,183,115,123,222,83,0,14,131,106,218,18,32,162,225,164,208,173,143,11,195,92,175,43,204,59,209,161,68,103,176,205,14,84,24,241,139,244,236,127,184,213,93,241,90,4,59,173,237,248,223,170,111,197,146,168,102,60,147,236,161,49,180,84,245,235,205,51,201,241,58,55,202,141,42,84,33,184,19,196,125,239,163,151,78,5,241,90,244,26,81,103,34,106,82,98,193,131,139,62,45,47,89,112,165,192,247,168,40,254,12,230,227,110,225,237,8,150,233,250,174,101,199,8,230,11,64,64,46,248,41,125,130,233,239,198,110,62,85,100,236,197,198,78,17,253,168,127,99,4,161,55,233,150,185,215,76,238,57,37,108,194,220,18,36,168,40,88,107,204,99,87,110,111,139,150,126,128,171,254,5,246,110,22,143,184,59,53,147,154,55,101,103,242,122,14,98,215,87,220,234,22,101,62,155,16,187,207,220,217,81,207,3,165,50,100,214,241,84,237,78,213,178,19,50,55,51,5,201,168,232,195,83,101,230,163,213,83,5,24,57,121,21,71,215,80,232,120,12,47,125,30,48,70,122,189,62,57,87,157,156,120,73,230,182,104,9,54,237,102,247,192,148,87,219,49,160,78,18,146,154,244,144,87,177,161,17,223,92,187,147,179,188,105,102,81,220,193,214,113,239,247,228,191,127,204,67,2,152,122,45,83,91,253,203,151,49,59,237,65,191,96,189,57,159,136,132,52,193,104,15,29,70,81,169,109,140,240,44,100,2,92,147,255,139,75,73,92,11,37,67,44,217,116,87,127,248,18,234,126,16,135,114,180,76,130,23,98,105,40,241,116,84,20,169,104,177,13,165,5,246,237,123,48,17,52,215,85,31,124,172,39,184,43,244,253,9,91,117,124,163,26,249,120,244,150,139,239,145,200,229,95,86,152,155,183,207,118,34,181,236,146,115,225,191,81,6,229,76,136,14,212,80,92,77,48,51,161,100,96,145,38,241,175,51,24,67,143,48]}],"Latitude":43.949100000288183,"Longitude":4.800676000847333,"Accuracy":19.975217819213871,"AuthInfo":null,"AuthTicket":{"Start":[241,224,161,87,94,67,7,167,95,187,156,143,149,161,50,103,48,176,128,66,81,145,116,144,251,186,134,226,110,76,141,75,218,68,11,97,166,36,53,24,182,210,158,25,43,19,235,211,51,43,108,223,229,113,180,111,242,86,139,233,152,169,120,244,163,209,117,218,1,78,253,197,118,22,205,2,237,249,122,210],"ExpireTimestampMs":1484242860425,"End":[236,159,43,116,139,106,18,8,131,138,174,182,124,99,130,219]},"MsSinceLastLocationfix":6707}
   à PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PerformRemoteProcedureCall>d__7`1.MoveNext() dans C:\Users\Siakbary\Documents\Works\MyCode\PokeBOT\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:ligne 121
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PerformThrottledRemoteProcedureCall>d__8`1.MoveNext() dans C:\Users\Siakbary\Documents\Works\MyCode\PokeBOT\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:ligne 147
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__6`2.MoveNext() dans C:\Users\Siakbary\Documents\Works\MyCode\PokeBOT\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:ligne 60
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__3`2.MoveNext() dans C:\Users\Siakbary\Documents\Works\MyCode\PokeBOT\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:ligne 0
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PokemonGo.RocketAPI.Rpc.Fort.<StartGymBattle>d__8.MoveNext() dans C:\Users\Siakbary\Documents\Works\MyCode\PokeBOT\PokemonGo.RocketAPI\Rpc\Fort.cs:ligne 130
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PokemonGo.RocketAPI.Logic.Logic.<StartBattle>d__73.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PokemonGo.RocketAPI.Logic.Logic.<StartGymAttackLogic>d__70.MoveNext()
[18:23:38] there is problem :/
[18:23:42] Pokemon: Dragonite | ST:0/149
[18:23:42] You pokemon die, try use item revive
[18:23:47] BAD
[18:23:47] Pokemon: Snorlax | ST:0/254
[18:23:47] You pokemon die, try use item revive
[18:23:52] BAD
[18:23:52] Pokemon: Gyarados | ST:145/155
[18:23:52] You pokemon fine but critical, try use item potion
[18:23:52] Pokemon: Gyarados | ST:151/151
[18:23:52] You pokemon fine
[18:23:52] Pokemon: Snorlax | ST:246/246
[18:23:52] You pokemon fine
[18:23:52] Pokemon: Vaporeon | ST:203/203
[18:23:52] You pokemon fine
[18:23:54] Attacking Gym: La Grande Roue, DefendingPokemons:
Exeggutor
Rhydon
Exeggutor, 
Attacking: Exeggutor
[18:23:56] Start battle failed...., Error: PokemonGo.RocketAPI.Exceptions.InvalidResponseException: BAD REQUEST 
{"StatusCode":2,"RequestId":4314373603215804914,"Requests":[{"RequestType":135,"RequestMessage":[10,35,56,56,55,49,50,55,53,48,51,101,56,57,52,56,48,99,57,55,102,57,97,98,51,101,57,99,49,55,99,50,56,98,46,49,54,18,48,146,46,12,37,41,37,128,204,218,217,221,23,174,226,152,44,211,17,196,31,103,93,136,109,151,187,188,152,178,17,124,214,60,69,72,216,247,12,138,172,29,85,59,83,110,154,170,227,25,84,157,172,148,163,184,140,163,33,136,239,218,27,124,249,69,64,41,81,83,217,104,228,51,19,64]}],"PlatformRequests":[{"Type":6,"RequestMessage":[10,133,4,147,169,57,2,251,81,195,44,221,137,22,149,63,24,127,101,106,251,129,137,175,151,199,248,202,122,78,48,34,74,224,171,116,109,70,32,252,24,196,130,99,5,4,155,172,52,56,231,61,190,223,215,252,253,48,47,110,212,210,251,219,112,70,162,113,230,196,220,8,209,153,60,125,221,166,197,116,234,215,135,240,127,246,116,10,19,239,34,91,208,35,20,13,36,222,247,191,34,24,184,134,14,69,184,115,94,54,123,120,42,173,144,79,44,222,150,121,251,167,64,28,236,229,251,207,56,173,252,52,152,234,194,120,64,241,82,251,180,28,145,224,203,70,190,72,216,88,139,183,183,105,155,143,135,135,189,246,66,36,36,49,164,9,164,160,74,0,204,117,232,40,255,184,89,56,187,21,168,58,96,30,136,22,128,97,157,31,51,247,107,154,197,87,227,231,86,127,33,17,3,136,236,253,139,79,4,115,242,158,166,166,65,94,87,150,206,235,31,49,190,20,172,79,127,92,149,82,120,167,131,44,83,153,244,216,163,124,107,41,232,79,5,248,211,128,121,234,244,235,202,96,114,164,134,200,229,243,12,107,28,94,121,214,235,209,35,185,251,215,251,134,170,253,168,182,36,110,132,198,167,108,68,162,151,151,119,231,135,132,209,116,139,60,173,223,139,23,164,176,133,230,135,142,108,15,188,11,35,72,6,94,90,222,254,112,199,163,200,121,21,218,172,237,241,53,199,33,51,19,228,188,144,133,152,138,198,169,228,14,247,102,135,91,76,81,84,175,168,70,28,100,227,94,9,164,136,181,206,176,139,35,39,166,202,126,3,36,0,124,29,10,70,4,184,221,209,163,53,142,178,253,49,128,96,163,160,2,157,68,153,214,29,43,201,248,3,42,58,87,234,10,42,73,24,195,1,207,154,107,80,130,206,115,70,138,50,91,113,226,254,60,200,103,51,145,49,209,96,33,198,50,140,214,249,174,218,255,2,252,99,203,164,118,193,165,92,31,185,37,208,95,2,77,150,121,81,159,100,20,41,160,251,147,24,40,201,15,198,62,253,248,65,1,56,227,160,139,42,34,146,197,23,131,201,56,245,23,205,40,208,83,234,185,134,192,159,203,136,36,163,67,125,148,59,87,62,121,243,26,132,33,36,138,125,3,70,48]}],"Latitude":43.949100000288183,"Longitude":4.800676000847333,"Accuracy":19.975217819213871,"AuthInfo":null,"AuthTicket":{"Start":[241,224,161,87,94,67,7,167,95,187,156,143,149,161,50,103,48,176,128,66,81,145,116,144,251,186,134,226,110,76,141,75,218,68,11,97,166,36,53,24,182,210,158,25,43,19,235,211,51,43,108,223,229,113,180,111,242,86,139,233,152,169,120,244,163,209,117,218,1,78,253,197,118,22,205,2,237,249,122,210],"ExpireTimestampMs":1484242860425,"End":[236,159,43,116,139,106,18,8,131,138,174,182,124,99,130,219]},"MsSinceLastLocationfix":7810}
   à PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PerformRemoteProcedureCall>d__7`1.MoveNext() dans C:\Users\Siakbary\Documents\Works\MyCode\PokeBOT\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:ligne 121
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PerformThrottledRemoteProcedureCall>d__8`1.MoveNext() dans C:\Users\Siakbary\Documents\Works\MyCode\PokeBOT\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:ligne 147
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__6`2.MoveNext() dans C:\Users\Siakbary\Documents\Works\MyCode\PokeBOT\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:ligne 60
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__3`2.MoveNext() dans C:\Users\Siakbary\Documents\Works\MyCode\PokeBOT\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:ligne 0
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PokemonGo.RocketAPI.Rpc.Fort.<StartGymBattle>d__8.MoveNext() dans C:\Users\Siakbary\Documents\Works\MyCode\PokeBOT\PokemonGo.RocketAPI\Rpc\Fort.cs:ligne 130
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PokemonGo.RocketAPI.Logic.Logic.<StartBattle>d__73.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PokemonGo.RocketAPI.Logic.Logic.<StartGymAttackLogic>d__70.MoveNext()
[18:23:56] there is problem :/
[18:24:01] Pokemon: Dragonite | ST:0/149
[18:24:01] You pokemon die, try use item revive
[18:24:05] BAD
[18:24:05] Pokemon: Snorlax | ST:0/254
[18:24:05] You pokemon die, try use item revive
[18:24:10] BAD
[18:24:10] Pokemon: Gyarados | ST:145/155
[18:24:10] You pokemon fine but critical, try use item potion
[18:24:10] Pokemon: Gyarados | ST:151/151
[18:24:10] You pokemon fine
[18:24:10] Pokemon: Snorlax | ST:246/246
[18:24:10] You pokemon fine
[18:24:10] Pokemon: Vaporeon | ST:203/203
[18:24:10] You pokemon fine
[18:24:12] Attacking Gym: La Grande Roue, DefendingPokemons:
Exeggutor
Rhydon
Exeggutor, 
Attacking: Exeggutor
[18:24:14] Start battle failed...., Error: PokemonGo.RocketAPI.Exceptions.InvalidResponseException: BAD REQUEST 
{"StatusCode":2,"RequestId":3015511308914133556,"Requests":[{"RequestType":135,"RequestMessage":[10,35,56,56,55,49,50,55,53,48,51,101,56,57,52,56,48,99,57,55,102,57,97,98,51,101,57,99,49,55,99,50,56,98,46,49,54,18,48,146,46,12,37,41,37,128,204,218,217,221,23,174,226,152,44,211,17,196,31,103,93,136,109,151,187,188,152,178,17,124,214,60,69,72,216,247,12,138,172,29,85,59,83,110,154,170,227,25,84,157,172,148,163,184,140,163,33,136,239,218,27,124,249,69,64,41,81,83,217,104,228,51,19,64]}],"PlatformRequests":[{"Type":6,"RequestMessage":[10,133,4,147,169,57,2,237,90,136,237,230,251,148,128,68,109,50,213,18,163,55,125,125,98,1,159,174,159,71,126,71,99,137,250,236,88,8,175,238,136,166,244,2,253,14,53,3,110,140,254,192,75,122,236,247,213,143,32,253,212,147,23,46,92,131,135,77,49,206,170,142,165,151,169,124,217,60,219,249,159,167,112,247,22,133,74,1,221,83,5,226,174,101,230,70,108,166,108,139,40,40,81,47,205,0,68,54,169,155,138,106,102,178,224,207,171,6,254,66,144,103,228,164,208,83,105,102,215,84,105,153,201,88,247,73,30,230,238,166,138,229,81,232,8,133,47,250,101,110,70,208,119,206,38,40,92,60,132,46,2,101,23,201,146,224,9,9,86,169,125,32,174,39,102,88,147,251,190,226,110,70,74,149,89,176,186,133,98,193,62,130,250,62,211,96,118,93,190,52,130,168,249,173,120,246,39,55,203,1,182,149,145,195,61,40,97,183,78,32,143,147,50,150,238,13,0,46,3,9,93,75,53,64,20,93,16,197,94,199,58,191,58,183,157,157,75,49,24,7,4,122,98,20,62,2,248,57,162,174,89,27,68,248,77,253,200,45,96,168,82,231,236,56,24,63,217,151,114,52,26,59,38,255,53,17,43,118,33,16,100,121,12,173,178,61,14,41,14,128,170,30,49,152,71,97,100,39,243,62,80,50,139,247,215,231,227,128,194,154,115,71,126,156,70,21,67,149,96,59,88,139,137,101,78,138,183,184,200,244,215,234,61,111,94,121,132,176,61,158,8,90,112,48,191,108,37,32,57,36,40,216,243,70,57,185,180,64,76,253,75,197,145,163,217,1,234,181,130,10,179,87,100,186,65,194,230,42,171,211,228,138,29,2,243,153,41,140,213,204,13,225,51,211,89,165,227,8,161,198,192,37,201,157,5,148,197,159,243,220,40,227,244,8,92,52,202,149,164,236,52,123,25,26,110,122,142,165,74,150,9,92,116,166,49,115,0,128,140,175,142,194,182,115,102,203,149,121,152,101,255,83,123,237,40,215,107,201,212,251,31,151,184,215,107,238,9,105,5,6,137,221,235,188,2,214,1,19,227,48,211,100,204,44,70,199,201,43,173,255,98,178,111,160,230,254,105,252,155,205,191,85,183,123,59,237,150,91,76,48]}],"Latitude":43.949100000288183,"Longitude":4.800676000847333,"Accuracy":19.975217819213871,"AuthInfo":null,"AuthTicket":{"Start":[241,224,161,87,94,67,7,167,95,187,156,143,149,161,50,103,48,176,128,66,81,145,116,144,251,186,134,226,110,76,141,75,218,68,11,97,166,36,53,24,182,210,158,25,43,19,235,211,51,43,108,223,229,113,180,111,242,86,139,233,152,169,120,244,163,209,117,218,1,78,253,197,118,22,205,2,237,249,122,210],"ExpireTimestampMs":1484242860425,"End":[236,159,43,116,139,106,18,8,131,138,174,182,124,99,130,219]},"MsSinceLastLocationfix":6976}
   à PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PerformRemoteProcedureCall>d__7`1.MoveNext() dans C:\Users\Siakbary\Documents\Works\MyCode\PokeBOT\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:ligne 121
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PerformThrottledRemoteProcedureCall>d__8`1.MoveNext() dans C:\Users\Siakbary\Documents\Works\MyCode\PokeBOT\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:ligne 147
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__6`2.MoveNext() dans C:\Users\Siakbary\Documents\Works\MyCode\PokeBOT\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:ligne 60
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__3`2.MoveNext() dans C:\Users\Siakbary\Documents\Works\MyCode\PokeBOT\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:ligne 0
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PokemonGo.RocketAPI.Rpc.Fort.<StartGymBattle>d__8.MoveNext() dans C:\Users\Siakbary\Documents\Works\MyCode\PokeBOT\PokemonGo.RocketAPI\Rpc\Fort.cs:ligne 130
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PokemonGo.RocketAPI.Logic.Logic.<StartBattle>d__73.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PokemonGo.RocketAPI.Logic.Logic.<StartGymAttackLogic>d__70.MoveNext()
[18:24:14] there is problem :/

**Comment by Titiocb13** [comment]
Can you add an option "farm gym" (like "catch pokemon" or "farm pokestop") on the live settings ?

**Comment by akbaryahya** [comment]
farm gym =meaning only gather coins and put pokemon in gym (just look for our team)? so they do not attack
