### ISSUE TITLE
Share Log SessionInvalidated

### ISSUE THREAD

**Issue by akbaryahya** [akbaryahya/PokeBot#72]
Since latest API updates bot you always get SessionInvalidated, we suggest you use version PokeBOT V8.1, but if you want help me, fix this please share your log here each getting error or stuck (full log).

**Comment by fronTAIR** [comment]
[log-20170407.txt](https://github.com/akbaryahya/PokeBot/files/905599/log-20170407.txt)

**Comment by akbaryahya** [comment]
close team pokehash have fixed this problem

**Comment by vickpin** [comment]
Please scrips WiFi.id js or json
