### ISSUE TITLE
Can't Auto Transfer.....

### ISSUE THREAD

**Issue by dafunsong** [akbaryahya/PokeBot#73]
Dear Sir,

I had enabled the function of Auto Transfer as bellowing.
But it didn't work,
Should I do anything more?

![image](https://cloud.githubusercontent.com/assets/26339461/24698953/0a59c306-1a25-11e7-91c1-8d07561f8a11.png)

Thanks for your kindly help.

**Comment by akbaryahya** [comment]
auto transfer will be done every pokemon you full
