### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by PeshBG** [akbaryahya/PokeBot#76]
7-Zip (A) 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18

Processing archive: Update.zip

Error: Can not open file as archive

**Comment by akbaryahya** [comment]
Please update manual, Previous version is not working

**Comment by PeshBG** [comment]
thanks :) just a small remark, avast blocked the new build. maybe you forgot to sign it or something like that.

**Comment by akbaryahya** [comment]
Yes it may be because not sign file, But if I do it the dll which has no sign will not work
