### ISSUE TITLE
Bot bloqued when i put resfresh egg or item

### ISSUE THREAD

**Issue by Titiocb13** [akbaryahya/PokeBot#8]
On the egg or item tab, when you click on "refresh" during an action bot ("the are ongoing in progess, please wait...") or not, the bot is bloqued : when can't change tab or close the GUI window.

**Comment by Ajoi1986** [comment]
Yup.. similar problem

**Comment by akbaryahya** [comment]
stuck?, I tried did it happen but only on items and egg at time Incubate
