### ISSUE TITLE
Is Your Bot is Safe

### ISSUE THREAD

**Issue by jason86144** [akbaryahya/PokeBot#81]
I Getted Warning to not Using Third Party Software

**Comment by akbaryahya** [comment]
safe, make sure you do not snipe

**Comment by jason86144** [comment]
I Don't Snipe Anytime But Still Get Warning

**Comment by akbaryahya** [comment]
Once you get a warning, the warning can never be removed

**Comment by jason86144** [comment]
So If I Use Bot After Getting Warning I Get Banned Or Not

**Comment by akbaryahya** [comment]
not But you will not be able to find pokemon rare

**Comment by jason86144** [comment]
Mean Once I Get Warning I will Not Be able To find Rare Pokemon
