### ISSUE TITLE
Help to get Key PokeWP

### ISSUE THREAD

**Issue by orignguyen** [akbaryahya/PokeBot#86]
I forgot the information of my account logging in to siakbary.my.id and could not get the Key PokeWP for using with your new version.
I tried many ways to get it back as choosing "Forgot Password" or registering as new member.
Please help me!

My registered email: nhnguyen@hotmail.com

Thanks a lot!
OrigNguyen

**Comment by akbaryahya** [comment]
If you request a password please reset the password. We can not get it because it uses hash password

**Comment by orignguyen** [comment]
Please help me to reset my password. I could not do myself.
Tks

**Comment by akbaryahya** [comment]
https://api.siakbary.my.id/access.php?panel=forgot 

enter you email and check you email copy token and set new password

**Comment by orignguyen** [comment]
Thanks for help.


My problem's still there although I did as your instruction. There was no response after filling the forgot password form. Perhaps I put incorrect username.


My token email is rnZnuPtn61PvRNzZgOzaeEEDnTL5

It will be appreciate that you help to reset my account.

Thanks a lot,
OrigNguyen



________________________________
