### ISSUE TITLE
PokeWP doesn't seem to use pokestops anymore

### ISSUE THREAD

**Issue by scissors14** [akbaryahya/PokeBot#92]
![2](https://user-images.githubusercontent.com/20952475/30166902-532a6bc2-93aa-11e7-9cb3-04c2d8cd90e8.png)

I'm Using The Free Trial and using a Goman Hash Key, It seems to indicate that I've gotten the Wp by changing the color from blue to purple but it doesn't seem to get the items.

Thanks, I've gotten to level 25 with ease but I seem to be on my demise as I run out of pokeballs.

**Comment by akbaryahya** [comment]
can you upload tmp folder? (only last activity if file is large)

**Comment by scissors14** [comment]
[LastCoords-scissors14.txt](https://github.com/akbaryahya/PokeWP/files/1289499/LastCoords-scissors14.txt)
[log-20170831-scissors.txt](https://github.com/akbaryahya/PokeWP/files/1289497/log-20170831-scissors.txt)
[log-20170901-scissors.txt](https://github.com/akbaryahya/PokeWP/files/1289500/log-20170901-scissors.txt)
[log-20170902-scissors.txt](https://github.com/akbaryahya/PokeWP/files/1289498/log-20170902-scissors.txt)
[log-20170904-scissors.txt](https://github.com/akbaryahya/PokeWP/files/1289501/log-20170904-scissors.txt)
[log-20170905-scissors.txt](https://github.com/akbaryahya/PokeWP/files/1289504/log-20170905-scissors.txt)
[log-20170906-scissors.txt](https://github.com/akbaryahya/PokeWP/files/1289503/log-20170906-scissors.txt)
[log-20170907-scissors.txt](https://github.com/akbaryahya/PokeWP/files/1289502/log-20170907-scissors.txt)

Thanks.
