### ISSUE TITLE
Walking Radius weird

### ISSUE THREAD

**Issue by rainfall77** [akbaryahya/PokeBot#94]
Even I set to higher radius, the movement always in the smaller radius. 

once more thing, is that possible to Click on the pokemon image on the map, so it can AUTO fill the latitude and longitude in the CONTROL Tab, so it is easier to snipe nearby pokemon.

Thx for the great work anyway.

<img width="543" alt="screenshot_1" src="https://user-images.githubusercontent.com/31579589/30238337-e37b1c02-9577-11e7-81a5-e061fc4da26f.png">

**Comment by akbaryahya** [comment]
1.it's normal because there are pokestop available around there, so he stays there
2.we will try, later if you move map, on snipe will change same with "change location"
