### ISSUE TITLE
Pokemon Auto-Transfer system

### ISSUE THREAD

**Issue by Fantas1** [akbaryahya/PokeBot#96]
Hello,

I would like to know if PokeWP has a Pokemon Auto-Transfer system, because even the function is activated, PokeWP does nothing, thus filling the inventory and limiting the captioning of other pokemons.

Thank you!

**Comment by akbaryahya** [comment]
I do not know what it means.
auto-transfer only works if you select the pokemon you want to transfer and according cp / iv set
